parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    telegram_api.http_client:
        class: Closure
        factory:
            - 'Symfony\Component\HttpClient\HttpClient'
            - 'create'
        arguments:
            - base_uri: '%env(TELEGRAM_BASE_URI)%'

    App\Service\Telegram\TelegramAPI:
        class: App\Service\Telegram\TelegramAPI
        arguments:
            - "@telegram_api.http_client"
            - "%env(TELEGRAM_TOKEN)%"

    App\Service\Telegram\Bot:
        class: App\Service\Telegram\Bot
        public: true